services:
  web:
    build: .
    ports:
      - 5000:5000
    depends_on:
      - redis_db
  redis_db:
    image: redis:latest
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379
volumes:
  redis_data: {}
